---
title: "Manuscripts and Publications"
format:
  html:
    toc: true
---

## Preprints and Submitted Manuscripts

<ol reversed>

  <li>**Debnath JP**, Hossen K, Khandaker MS, Majid S, Islam MM, Arefin S, Sarker S*, Hossain T*, Dev PC*. <ins><strong>omicML: An integrative tool of bioinformatics and machine learning algorithms to identify transcriptomic biomarkers.</strong></ins> _Submitted to Bioinformatics (Oxford University Press)_, October 2025.</li><br>

  <li>**Debnath JP**, Hossen K, Datta U, Ghosh A*. <ins><strong>BioSalT: A multigene machine learning model for early salinity stress detection in Solanum lycopersicum.</strong></ins> _In preparation_, October 2025.</li><br>

  <li>**Debnath JP**, Hossain T*, Rahman P*. <ins><strong>Deep Neural Profiling Reveals RAP1GAP2 as a Latent Regulator of Tumor Invasion in Oropharyngeal Carcinoma.</strong></ins> _Under revision_, October 2025.</li><br>

  <li>**Debnath JP**, Hossen K, Islam MS, Sarker S, Dev PC*, Hossain T*. <ins><strong>DeepFold: A deep learning framework that emulates statistical models for differential gene expression analysis.</strong></ins> _In preparation_, 2025.</li><br>

</ol>


## Publications

<ol reversed>

  <li>**Debnath JP**, Hossen K, Sayed SB, Khandaker MS, Dev PC*, Sarker S*, Hossain T*. <ins><strong>Identification of potential biomarkers for 2022 Mpox virus infection: a transcriptomic network analysis and machine learning approach.</strong></ins> _Scientific Reports_ (Nature Publishing Group, UK), January 2025. [DOI pending]</li><br>

  <li>Sayed SB, Rabbi MA, **Debnath JP**, Hossen K, Ghosh A*. <ins><strong>Genome-wide identification and characterization of m6A regulatory genes in soybean: Insights into evolution, miRNA interactions, and stress responses.</strong></ins> _PLOS One_, July 2025. [DOI pending]</li><br>

  <li>**Debnath JP**, Hossen K, Khandaker MS, Majid S, Islam MM, Arefin S, Sarker S*, Hossain T*, Dev PC*. <ins><strong>omicML: An integrative tool of bioinformatics and machine learning algorithms to identify transcriptomic biomarkers.</strong></ins> _Submitted to Bioinformatics_, October 2025.</li><br>

  <li>**Debnath JP**, Hossain T*, Rahman P*. <ins><strong>Deep Neural Profiling Reveals RAP1GAP2 as a Latent Regulator of Tumor Invasion in Oropharyngeal Carcinoma.</strong></ins> _Under revision_, 2025.</li><br>

  <li>**Debnath JP**, Hossen K, Datta U, Ghosh A*. <ins><strong>BioSalT (Biomarkers of Salinity Stress in Tomato): A Multigene Machine Learning Model for Early Salinity Stress Detection in _Solanum lycopersicum_.</strong></ins> _Manuscript under preparation_, 2025.</li><br>

  <li>Khandaker MS, Islam SMR U*, **Debnath JP**, Hossen K, Razib SFA, Dey BP. <ins><strong>Molecular screening of Head and Neck Squamous Cell Carcinoma patients for Human Papillomavirus.</strong></ins> _Presented at IPVS 2025 (Bangkok, Thailand)_ and _the 11th Wuhan International Symposium on Modern Virology & Viruses 2025 (Wuhan, China)_; sequence data published in _NCBI GenBank (public repository)._</li><br>

  <li>**Debnath JP**, Hossen K, Dev PC*, Hossain T*. <ins><strong>Synthesis and Application of Ag-deposited Ni/rGO nanospheres in Glucose Sensing, Antibacterial Properties, and Antioxidant Activity.</strong></ins> _Funded by SUST Research Center_, 2025.</li><br>

</ol>
